spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  cloud:
    gateway:
      mvc:
        routes:
          - id: MyBeerRestProjectWithOAuth2
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/*
          - id: ReactiveServer
            uri: http://localhost:8082
            predicates:
              - Path=/api/v2/*
          - id: reactiveMongoWithOAuth2
            uri: http://localhost:8083
            predicates:
              - Path=/api/v3/*
